---
- name: installing httpd using handlers
  hosts: redhat
  become: yes
  tasks:
     - name: installing redhat
       yum:
          name: httpd
          state: present
       notify: restarting the service
     - name: deployment of code into httpd web
       copy:
           src: /home/ansible/index.html
           dest: /var/www/html
       notify: restarting the service
  handlers:
    - name: restarting the service
      service:
              name: httpd
              state: restarted      
