---
- name: ignoring tasks errors
  hosts: all
  tasks:
     - name: shell command
       shell: ls
       ignore_errors: yes
       register: out
     - name: printing
       debug:
           msg: "{{out}}"
