---
- hosts: all
  become: yes
  tasks:
     - name: installing apache2
       apt:
          name: apache2
          state: present
       when: ansible_distribution == "Ubuntu"
     - name: installing httpd
       yum:
          name: httpd
          state: present
       when: ansible_distribution == "RedHat"
