- name: installing "{{pkg}}"
  apt:
     name: "{{pkg}}"
     state: "{{state1}}"
- name: deployment
  copy:
      src: "{{sr}}"
      dest: "{{des}}"
- name: restarting
  service:
         name: "{{pkg}}"
         state: "{{state2}}"

